#ifndef	_DAVINCI_BOOT_H_
#define	_DAVINCI_BOOT_H_

#include <asm/arch/hardware.h>

#ifdef CONFIG_SOC_DA8XX
#define BOOTCFG_REG			(DAVINCI_BOOTCFG_BASE + 0x20)
#define BOOTCFG_REG_DEVICE_MASK		0x1F

#define BOOTCFG_DEVICE_NOR		0x02
#define BOOTCFG_DEVICE_NAND8		0x0E
#define BOOTCFG_DEVICE_NAND16		0x10
#define BOOTCFG_DEVICE_MMC_OR_SD0	0x1C
#define BOOTCFG_DEVICE_I2C0_EEPROM	0x00
#define BOOTCFG_DEVICE_I2C1_EEPROM	0x06
#define BOOTCFG_DEVICE_I2C0_SLAVE	0x01
#define BOOTCFG_DEVICE_I2C1_SLAVE	0x07
#define BOOTCFG_DEVICE_SPI0_EEPROM	0x08
#define BOOTCFG_DEVICE_SPI1_EEPROM	0x09
#define BOOTCFG_DEVICE_SPI0_FLASH	0x0A
#define BOOTCFG_DEVICE_SPI1_FLASH	0x0C
#define BOOTCFG_DEVICE_SPI0_SLAVE	0x12
#define BOOTCFG_DEVICE_SPI1_SLAVE	0x13
#define BOOTCFG_DEVICE_UART0		0x16
#define BOOTCFG_DEVICE_UART1		0x17
#define BOOTCFG_DEVICE_UART2		0x14
#define BOOTCFG_DEVICE_HPI		0x04
#define BOOTCFG_DEVICE_EMULATION_DEBUG	0x1E
#endif /* CONFIG_SOC_DA8XX */

#endif /* _DAVINCI_BOOT_H_ */
